language: objective-c
osx_image: xcode8
podfile: Example/Podfile

before_install:
    - gem install cocoapods --quiet
    - "xcrun instruments -w 'iPhone 5 (9.0)' || true"
    - sleep 20
    - sleep 20
    - sleep 20
    - perl allowAccess
script:
    - "xcodebuild -workspace Example/SwiftAddressBookExample.xcworkspace -scheme SwiftAddressBookTests -sdk iphonesimulator -destination platform='iOS Simulator','OS=9.0',name='iPhone 5' test"
